title: Jordan Ye # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  Hi, I'm Jordan Ye, a business analyst passionate about understanding consumer psychology and leveraging data to drive impactful decisions. My portfolio highlights projects in both data analytics and visualization, reflecting my expertise in:
  <br><br>
  Business Analysis
  Consumer Behaviour
  Data Visualization
  Python & Tableau
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
