title: Jordan Ye # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Jordan Ye, a business analyst passionate about understanding consumer psychology and leveraging data to drive impactful decisions. My portfolio highlights projects in both data analytics and visualization, reflecting my expertise in:
  <br><br>
  I'm speicializing at
  <br><br>
  -Business Analysis
  <br><br>
  -Consumer Behaviour
  <br><br>
  -Data Visualization
  <br><br>
  -Python & Tableau
  <br><br>
  This website is built with Jekyll and GitHub Pages, using a minimal and modern design for clear project presentation.
  <br><br>
  <a href="www.linkedin.com/in/jiajun-ye">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/jordan.ye2240/vizzes">View My Tableau Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
